version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: marketplace
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["./wait-for.sh", "db:3306", "--", "./main"]

